
name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
env:
  WKROOT: /home/runner/work/wk-data/
  S3_URL: ${{secrets.S3_URL}}
  S3_BUCKET: ${{secrets.S3_BUCKET}}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: [3.10.12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}

      - name: Setup S3 Credentials
        env:
          S3_PUBLIC_KEY: ${{secrets.DIGITAL_OCEAN_SPACES_CI_ACCESS_KEY}}
          S3_SECRET_KEY: ${{secrets.DIGITAL_OCEAN_SPACES_CI_SECRET_KEY}}
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${S3_PUBLIC_KEY}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${S3_SECRET_KEY}" >> ~/.aws/credentials

      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      #----------------------------------------------
      # Cache input data
      #----------------------------------------------
      # - name: Cache input data
      #   uses: actions/cache@v2.1.6
      #   with:
      #     path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/tests/workDir
      #     key: ${{ runner.os }}-${{ hashFiles('$WKROOT') }}


      - name: Test
        run: |
          poetry run coverage run --module pytest --random-order
      - name: Verify test coverage
        run: |
          poetry run coverage xml -i

      - name: Analyze with Sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
